In [1]:
import os
import tensorflow as tf

In [2]:
tf.app.flags.DEFINE_string(
    "log_dir", os.path.join(os.path.dirname(os.path.abspath('__file__')), "logs"),
    "Directory where event logs are written to.")
tf.app.flags.DEFINE_string(
    "f", "", "kernel")
FLAGS = tf.app.flags.FLAGS

In [3]:
a = tf.constant(5.0, name="a")
b = tf.constant(10.1, name="b")

In [4]:
x = tf.add(a, b, name="add")
y = tf.div(a, b, name="divide")

In [5]:
with tf.Session() as sess:
    writer = tf.summary.FileWriter(os.path.expanduser(FLAGS.log_dir), sess.graph)
    print("a = ", sess.run(a))
    print("b = ", sess.run(b))
    print("a + b = ", sess.run(x))
    print("a/b = ", sess.run(y))

a =  5.0
b =  10.1
a + b =  15.1
a/b =  0.49504948


In [6]:
sess.close()

In [7]:
writer.close()

In [8]:
from tensorflow.python.framework import ops

In [9]:
weights = tf.Variable(tf.random_normal([2, 3], stddev=0.1), name="weights")
biases = tf.Variable(tf.zeros([3]), name="biases")
custom_variable = tf.Variable(tf.zeros([3]), name="custom")

all_variables_list = ops.get_collection(ops.GraphKeys.GLOBAL_VARIABLES)

In [10]:
#init specific variables
#variable_list_custom = [weights, custom_variable]

#init_custom_op = tf.variables_initializer(var_list=variable_list_custom)

In [11]:
#global variable init

#method 1
#init_all_op = tf.global_variables_initializer()
#method 2
init_all_op = tf.variables_initializer(var_list=all_variables_list)

In [12]:
WeightsNew = tf.Variable(weights.initialized_value(), name="WeightsNew")
init_WeightsNew_op = tf.variables_initializer(var_list=[WeightsNew])

In [14]:
with tf.Session() as sess:
    writer = tf.summary.FileWriter(os.path.expanduser(FLAGS.log_dir), sess.graph)
    sess.run(init_all_op)
    print(sess.run(weights))
    print(sess.run(biases))
    print(sess.run(custom_variable))
    #print(sess.run(WeightsNew))
    #sess.run(init_custom_op)
    sess.run(init_WeightsNew_op)
    print(sess.run(WeightsNew))
    
writer.close()
sess.close()

[[ 0.05051288  0.00494426 -0.07888947]
 [ 0.13680662 -0.07086431 -0.02419107]]
[0. 0. 0.]
[0. 0. 0.]
[[ 0.05051288  0.00494426 -0.07888947]
 [ 0.13680662 -0.07086431 -0.02419107]]
